import { Room } from './types';

export const MOCK_ROOMS: Room[] = [
    {
        id: '1',
        slug: 'sala-a',
        name: 'Sala A - La Catedral',
        description: 'Nuestra sala más grande, ideal para bandas completas. Acústica natural impecable y aire acondicionado.',
        capacity: 8,
        equipment: ['Batería DW Collector', 'Ampeg SVT-CL', 'Marshall JCM800', 'Fender Twin Reverb', 'PA JBL EON'],
        imageUrl: 'https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?auto=format&fit=crop&q=80&w=1000',
        pricePerHour: 15000,
        active: true,
    },
    {
        id: '2',
        slug: 'sala-b',
        name: 'Sala B - El Búnker',
        description: 'Sala seca y controlada, perfecta para ensayos de grabación o bandas de metal.',
        capacity: 6,
        equipment: ['Batería Pearl Masters', 'Gallien Krueger RB', 'Mesa Boogie Dual Rectifier', 'Vox AC30'],
        imageUrl: 'https://images.unsplash.com/photo-1514320291840-2e0a9bf2a9ae?auto=format&fit=crop&q=80&w=1000',
        pricePerHour: 12000,
        active: true,
    },
    {
        id: '3',
        slug: 'sala-c',
        name: 'Sala C - Vintage',
        description: 'Equipamiento clásico para un sonido cálido. Ideal para Jazz, Blues y Rock Clásico.',
        capacity: 5,
        equipment: ['Batería Ludwig Classic', 'Fender Bassman', 'Orange Rockerverb', 'Roland JC-120'],
        imageUrl: 'https://images.unsplash.com/photo-1525201548942-d8732f6617a0?auto=format&fit=crop&q=80&w=1000',
        pricePerHour: 12000,
        active: true,
    },
    {
        id: '4',
        slug: 'sala-d',
        name: 'Sala D - La Pecera',
        description: 'Sala compacta con visión directa a la sala de control. Ideal para tríos o cuartetos.',
        capacity: 4,
        equipment: ['Batería Yamaha Stage Custom', 'Markbass Little Mark', 'Fender Hot Rod', 'Marshall DSL'],
        imageUrl: 'https://images.unsplash.com/photo-1511379938547-c1f69419868d?auto=format&fit=crop&q=80&w=1000',
        pricePerHour: 10000,
        active: true,
    },
    {
        id: '5',
        slug: 'sala-e',
        name: 'Sala E - Acústica',
        description: 'Diseñada para ensayos acústicos o semi-unplugged. Ambiente íntimo.',
        capacity: 4,
        equipment: ['Cajón Peruano', 'Piano Digital Yamaha', 'Amplificador Acústico Fishman', 'PA Bose L1'],
        imageUrl: 'https://images.unsplash.com/photo-1510915361894-db8b60106cb1?auto=format&fit=crop&q=80&w=1000',
        pricePerHour: 9000,
        active: true,
    },
    {
        id: '6',
        slug: 'sala-f',
        name: 'Sala F - Estudio',
        description: 'Sala tratada para pre-producción. Incluye interfaz de grabación básica.',
        capacity: 5,
        equipment: ['Batería Tama Starclassic', 'Ampeg Portaflex', 'Kemper Profiler', 'Focusrite Scarlett 18i20'],
        imageUrl: 'https://images.unsplash.com/photo-1598653222000-6b7b7a552625?auto=format&fit=crop&q=80&w=1000',
        pricePerHour: 14000,
        active: true,
    },
];
